title: "Untitled"
description: ""
url: "https://oh-seokjin.github.io"
repository: "oh-seokjin/oh-seokjin.github.io"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: ""
  avatar: "assets/images/profile.jpg"
  bio: ""
  location: "Seoul, South Korea"
  email: "5hseokjin@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/seokjinoh/"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true
      show_date: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single      
      author_profile: true
      comments: true
      show_date: true

search: true
search_provider: "lunr"

comments:
  provider: "giscus"
  giscus:
    repo: "oh-seokjin/oh-seokjin.github.io"
    repo_id: "R_kgDORWCdSw"
    category_name: "Announcements"
    category_id: "DIC_kwDORWCdS84C2-70"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "light"